// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreatePlayer(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlayerStats = `-- name: CreatePlayerStats :one
INSERT INTO player_stats (player_id, match_type, season) 
VALUES ($1, $2, $3)
RETURNING id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded
`

type CreatePlayerStatsParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
}

func (q *Queries) CreatePlayerStats(ctx context.Context, arg CreatePlayerStatsParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, createPlayerStats, arg.PlayerID, arg.MatchType, arg.Season)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players
WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const editPlayerName = `-- name: EditPlayerName :one
UPDATE players
SET 
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type EditPlayerNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) EditPlayerName(ctx context.Context, arg EditPlayerNameParams) (Player, error) {
	row := q.db.QueryRow(ctx, editPlayerName, arg.ID, arg.Name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, name, created_at, updated_at FROM players
WHERE id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerSeasonalStats = `-- name: GetPlayerSeasonalStats :one
SELECT id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded FROM player_stats
WHERE player_id = $1
AND match_type = $2
AND season = $3
`

type GetPlayerSeasonalStatsParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
}

func (q *Queries) GetPlayerSeasonalStats(ctx context.Context, arg GetPlayerSeasonalStatsParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, getPlayerSeasonalStats, arg.PlayerID, arg.MatchType, arg.Season)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}

const getPlayerStats = `-- name: GetPlayerStats :many
SELECT id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded FROM player_stats
WHERE player_id = $1
`

func (q *Queries) GetPlayerStats(ctx context.Context, playerID uuid.UUID) ([]PlayerStat, error) {
	rows, err := q.db.Query(ctx, getPlayerStats, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerStat{}
	for rows.Next() {
		var i PlayerStat
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.MatchType,
			&i.Season,
			&i.Wins,
			&i.Losses,
			&i.Otl,
			&i.Streak,
			&i.LongestStreak,
			&i.Scored,
			&i.Conceded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name, created_at, updated_at FROM players
ORDER BY name
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonalStats = `-- name: ListSeasonalStats :many
SELECT id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded FROM player_stats
WHERE match_type = $1
AND season = $2
ORDER BY wins
`

type ListSeasonalStatsParams struct {
	MatchType string `json:"match_type"`
	Season    int32  `json:"season"`
}

func (q *Queries) ListSeasonalStats(ctx context.Context, arg ListSeasonalStatsParams) ([]PlayerStat, error) {
	rows, err := q.db.Query(ctx, listSeasonalStats, arg.MatchType, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerStat{}
	for rows.Next() {
		var i PlayerStat
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.MatchType,
			&i.Season,
			&i.Wins,
			&i.Losses,
			&i.Otl,
			&i.Streak,
			&i.LongestStreak,
			&i.Scored,
			&i.Conceded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerStatsLoss = `-- name: UpdatePlayerStatsLoss :one
UPDATE player_stats
SET 
    losses = losses + 1,
    streak = 0,
    scored = $4,
    conceded = $5,
    updated_at = NOW()
WHERE player_id = $1
AND match_type = $2
AND season = $3
RETURNING id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded
`

type UpdatePlayerStatsLossParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
	Scored    *int32    `json:"scored"`
	Conceded  *int32    `json:"conceded"`
}

func (q *Queries) UpdatePlayerStatsLoss(ctx context.Context, arg UpdatePlayerStatsLossParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatsLoss,
		arg.PlayerID,
		arg.MatchType,
		arg.Season,
		arg.Scored,
		arg.Conceded,
	)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}

const updatePlayerStatsOtl = `-- name: UpdatePlayerStatsOtl :one
UPDATE player_stats
SET 
    otl = otl + 1,
    scored = $4,
    conceded = $5,
    updated_at = NOW()
WHERE player_id = $1
AND match_type = $2
AND season = $3
RETURNING id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded
`

type UpdatePlayerStatsOtlParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
	Scored    *int32    `json:"scored"`
	Conceded  *int32    `json:"conceded"`
}

func (q *Queries) UpdatePlayerStatsOtl(ctx context.Context, arg UpdatePlayerStatsOtlParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatsOtl,
		arg.PlayerID,
		arg.MatchType,
		arg.Season,
		arg.Scored,
		arg.Conceded,
	)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}

const updatePlayerStatsWin = `-- name: UpdatePlayerStatsWin :one
UPDATE player_stats
SET 
    wins = wins + 1,
    streak = streak + 1,
    longest_streak = $3,
    scored = $4,
    conceded = $5,
    updated_at = NOW()
WHERE player_id = $1
AND match_type = $2
AND season = $3
RETURNING id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded
`

type UpdatePlayerStatsWinParams struct {
	PlayerID      uuid.UUID `json:"player_id"`
	MatchType     string    `json:"match_type"`
	LongestStreak *int32    `json:"longest_streak"`
	Scored        *int32    `json:"scored"`
	Conceded      *int32    `json:"conceded"`
}

func (q *Queries) UpdatePlayerStatsWin(ctx context.Context, arg UpdatePlayerStatsWinParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatsWin,
		arg.PlayerID,
		arg.MatchType,
		arg.LongestStreak,
		arg.Scored,
		arg.Conceded,
	)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}
