// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePlayer(ctx context.Context, name string) (Player, error)
	CreatePlayerStats(ctx context.Context, arg CreatePlayerStatsParams) (PlayerStat, error)
	DeletePlayer(ctx context.Context, id uuid.UUID) error
	EditPlayerName(ctx context.Context, arg EditPlayerNameParams) (Player, error)
	GetPlayer(ctx context.Context, id uuid.UUID) (Player, error)
	GetPlayerSeasonalStats(ctx context.Context, arg GetPlayerSeasonalStatsParams) (PlayerStat, error)
	GetPlayerStats(ctx context.Context, playerID pgtype.UUID) ([]PlayerStat, error)
	ListPlayers(ctx context.Context) ([]Player, error)
	ListSeasonalStats(ctx context.Context, arg ListSeasonalStatsParams) ([]PlayerStat, error)
	UpdatePlayerStatsLoss(ctx context.Context, arg UpdatePlayerStatsLossParams) (PlayerStat, error)
	UpdatePlayerStatsOtl(ctx context.Context, arg UpdatePlayerStatsOtlParams) (PlayerStat, error)
	UpdatePlayerStatsWin(ctx context.Context, arg UpdatePlayerStatsWinParams) (PlayerStat, error)
}

var _ Querier = (*Queries)(nil)
