// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addPlayerToMatch = `-- name: AddPlayerToMatch :one
INSERT INTO match_players (match_id, player_id, color)
VALUES ($1, $2, $3)
RETURNING id, match_id, player_id, color
`

type AddPlayerToMatchParams struct {
	MatchID  uuid.UUID `json:"match_id"`
	PlayerID uuid.UUID `json:"player_id"`
	Color    string    `json:"color"`
}

func (q *Queries) AddPlayerToMatch(ctx context.Context, arg AddPlayerToMatchParams) (MatchPlayer, error) {
	row := q.db.QueryRow(ctx, addPlayerToMatch, arg.MatchID, arg.PlayerID, arg.Color)
	var i MatchPlayer
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.Color,
	)
	return i, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (match_type, season)
VALUES ($1, $2)
RETURNING id, match_type, season, blue_score, red_score, is_completed, created_at, updated_at
`

type CreateMatchParams struct {
	MatchType string `json:"match_type"`
	Season    int32  `json:"season"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch, arg.MatchType, arg.Season)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Season,
		&i.BlueScore,
		&i.RedScore,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraft = `-- name: DeleteDraft :exec
DELETE FROM matches
WHERE is_completed = FALSE
AND id = $1
`

func (q *Queries) DeleteDraft(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraft, id)
	return err
}

const getDrafts = `-- name: GetDrafts :many
SELECT id, match_type, season, blue_score, red_score, is_completed, created_at, updated_at FROM matches
WHERE is_completed = FALSE
`

func (q *Queries) GetDrafts(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, getDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.MatchType,
			&i.Season,
			&i.BlueScore,
			&i.RedScore,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatch = `-- name: GetMatch :one
SELECT id, match_type, season, blue_score, red_score, is_completed, created_at, updated_at FROM matches
WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Season,
		&i.BlueScore,
		&i.RedScore,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayersFromMatch = `-- name: GetPlayersFromMatch :many
SELECT id, match_id, player_id, color FROM match_players
WHERE match_id = $1
`

func (q *Queries) GetPlayersFromMatch(ctx context.Context, matchID uuid.UUID) ([]MatchPlayer, error) {
	rows, err := q.db.Query(ctx, getPlayersFromMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchPlayer{}
	for rows.Next() {
		var i MatchPlayer
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegisteredMatches = `-- name: GetRegisteredMatches :many
SELECT id, match_type, season, blue_score, red_score, is_completed, created_at, updated_at FROM matches
WHERE is_completed = TRUE
`

func (q *Queries) GetRegisteredMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.Query(ctx, getRegisteredMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.MatchType,
			&i.Season,
			&i.BlueScore,
			&i.RedScore,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonMatches = `-- name: GetSeasonMatches :many
SELECT id, match_type, season, blue_score, red_score, is_completed, created_at, updated_at FROM matches
WHERE is_completed = TRUE
AND match_type = $1
AND season = $2
`

type GetSeasonMatchesParams struct {
	MatchType string `json:"match_type"`
	Season    int32  `json:"season"`
}

func (q *Queries) GetSeasonMatches(ctx context.Context, arg GetSeasonMatchesParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, getSeasonMatches, arg.MatchType, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.MatchType,
			&i.Season,
			&i.BlueScore,
			&i.RedScore,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerMatch = `-- name: RegisterMatch :one
UPDATE matches
SET 
    blue_score = $2,
    red_score = $3,
    is_completed = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, match_type, season, blue_score, red_score, is_completed, created_at, updated_at
`

type RegisterMatchParams struct {
	ID        uuid.UUID `json:"id"`
	BlueScore int32     `json:"blue_score"`
	RedScore  int32     `json:"red_score"`
}

func (q *Queries) RegisterMatch(ctx context.Context, arg RegisterMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, registerMatch, arg.ID, arg.BlueScore, arg.RedScore)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.Season,
		&i.BlueScore,
		&i.RedScore,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
