// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Match struct {
	ID          uuid.UUID          `json:"id"`
	MatchType   string             `json:"match_type"`
	Season      int32              `json:"season"`
	BlueScore   int32              `json:"blue_score"`
	RedScore    int32              `json:"red_score"`
	IsCompleted bool               `json:"is_completed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MatchPlayer struct {
	ID        uuid.UUID          `json:"id"`
	MatchID   uuid.UUID          `json:"match_id"`
	PlayerID  uuid.UUID          `json:"player_id"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Player struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlayerStat struct {
	ID            uuid.UUID          `json:"id"`
	PlayerID      uuid.UUID          `json:"player_id"`
	MatchType     string             `json:"match_type"`
	Season        int32              `json:"season"`
	Wins          int32              `json:"wins"`
	Losses        int32              `json:"losses"`
	Otl           int32              `json:"otl"`
	Streak        int32              `json:"streak"`
	LongestStreak int32              `json:"longest_streak"`
	Scored        int32              `json:"scored"`
	Conceded      int32              `json:"conceded"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
