// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreatePlayer(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players
WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT 
    p.name,
    ps.id, ps.player_id, ps.match_type, ps.season, ps.wins, ps.losses, ps.otl, ps.streak, ps.longest_streak, ps.scored, ps.conceded,
    2 * ps.wins + ps.otl AS points,
    ps.wins + ps.losses + ps.otl AS played,
    CASE 
        WHEN (ps.wins + ps.losses + ps.otl) = 0 THEN 0
        ELSE ps.wins / (ps.wins + ps.losses + ps.otl)
    END AS win_rate,
    CASE 
        WHEN ps.conceded = 0 THEN 0
        ELSE ps.scored / ps.conceded
    END AS efficiency_rate
FROM player_stats ps
JOIN players p ON p.id = ps.player_id
WHERE ps.match_type = $1
AND ps.season = $2
ORDER BY points DESC
`

type GetLeaderboardParams struct {
	MatchType string `json:"match_type"`
	Season    int32  `json:"season"`
}

type GetLeaderboardRow struct {
	Name           string      `json:"name"`
	ID             uuid.UUID   `json:"id"`
	PlayerID       uuid.UUID   `json:"player_id"`
	MatchType      string      `json:"match_type"`
	Season         int32       `json:"season"`
	Wins           int32       `json:"wins"`
	Losses         int32       `json:"losses"`
	Otl            int32       `json:"otl"`
	Streak         int32       `json:"streak"`
	LongestStreak  int32       `json:"longest_streak"`
	Scored         int32       `json:"scored"`
	Conceded       int32       `json:"conceded"`
	Points         int32       `json:"points"`
	Played         int32       `json:"played"`
	WinRate        interface{} `json:"win_rate"`
	EfficiencyRate interface{} `json:"efficiency_rate"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.MatchType, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardRow{}
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.Name,
			&i.ID,
			&i.PlayerID,
			&i.MatchType,
			&i.Season,
			&i.Wins,
			&i.Losses,
			&i.Otl,
			&i.Streak,
			&i.LongestStreak,
			&i.Scored,
			&i.Conceded,
			&i.Points,
			&i.Played,
			&i.WinRate,
			&i.EfficiencyRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, name, created_at, updated_at FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByName = `-- name: GetPlayerByName :one
SELECT id, name, created_at, updated_at FROM players
WHERE name = $1
`

func (q *Queries) GetPlayerByName(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByName, name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerStatsByID = `-- name: GetPlayerStatsByID :one
SELECT 
    p.name,
    ps.id, ps.player_id, ps.match_type, ps.season, ps.wins, ps.losses, ps.otl, ps.streak, ps.longest_streak, ps.scored, ps.conceded,
    2 * ps.wins + ps.otl AS points,
    ps.wins + ps.losses + ps.otl AS played,
    CASE 
        WHEN (ps.wins + ps.losses + ps.otl) = 0 THEN 0
        ELSE ps.wins / (ps.wins + ps.losses + ps.otl)
    END AS win_rate,
    CASE 
        WHEN ps.conceded = 0 THEN 0
        ELSE ps.scored / ps.conceded
    END AS efficiency_rate
FROM player_stats ps
JOIN players p ON p.id = ps.player_id
WHERE ps.player_id = $1
AND ps.match_type = $2
AND ps.season = $3
`

type GetPlayerStatsByIDParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
}

type GetPlayerStatsByIDRow struct {
	Name           string      `json:"name"`
	ID             uuid.UUID   `json:"id"`
	PlayerID       uuid.UUID   `json:"player_id"`
	MatchType      string      `json:"match_type"`
	Season         int32       `json:"season"`
	Wins           int32       `json:"wins"`
	Losses         int32       `json:"losses"`
	Otl            int32       `json:"otl"`
	Streak         int32       `json:"streak"`
	LongestStreak  int32       `json:"longest_streak"`
	Scored         int32       `json:"scored"`
	Conceded       int32       `json:"conceded"`
	Points         int32       `json:"points"`
	Played         int32       `json:"played"`
	WinRate        interface{} `json:"win_rate"`
	EfficiencyRate interface{} `json:"efficiency_rate"`
}

func (q *Queries) GetPlayerStatsByID(ctx context.Context, arg GetPlayerStatsByIDParams) (GetPlayerStatsByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlayerStatsByID, arg.PlayerID, arg.MatchType, arg.Season)
	var i GetPlayerStatsByIDRow
	err := row.Scan(
		&i.Name,
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
		&i.Points,
		&i.Played,
		&i.WinRate,
		&i.EfficiencyRate,
	)
	return i, err
}

const getPlayerStatsByName = `-- name: GetPlayerStatsByName :one
SELECT 
    p.name,
    ps.id, ps.player_id, ps.match_type, ps.season, ps.wins, ps.losses, ps.otl, ps.streak, ps.longest_streak, ps.scored, ps.conceded,
    2 * ps.wins + ps.otl AS points,
    ps.wins + ps.losses + ps.otl AS played,
    CASE 
        WHEN (ps.wins + ps.losses + ps.otl) = 0 THEN 0
        ELSE ps.wins / (ps.wins + ps.losses + ps.otl)
    END AS win_rate,
    CASE 
        WHEN ps.conceded = 0 THEN 0
        ELSE ps.scored / ps.conceded
    END AS efficiency_rate
FROM player_stats ps
JOIN players p ON p.id = ps.player_id
WHERE p.name = $1
AND ps.match_type = $2
AND ps.season = $3
`

type GetPlayerStatsByNameParams struct {
	Name      string `json:"name"`
	MatchType string `json:"match_type"`
	Season    int32  `json:"season"`
}

type GetPlayerStatsByNameRow struct {
	Name           string      `json:"name"`
	ID             uuid.UUID   `json:"id"`
	PlayerID       uuid.UUID   `json:"player_id"`
	MatchType      string      `json:"match_type"`
	Season         int32       `json:"season"`
	Wins           int32       `json:"wins"`
	Losses         int32       `json:"losses"`
	Otl            int32       `json:"otl"`
	Streak         int32       `json:"streak"`
	LongestStreak  int32       `json:"longest_streak"`
	Scored         int32       `json:"scored"`
	Conceded       int32       `json:"conceded"`
	Points         int32       `json:"points"`
	Played         int32       `json:"played"`
	WinRate        interface{} `json:"win_rate"`
	EfficiencyRate interface{} `json:"efficiency_rate"`
}

func (q *Queries) GetPlayerStatsByName(ctx context.Context, arg GetPlayerStatsByNameParams) (GetPlayerStatsByNameRow, error) {
	row := q.db.QueryRow(ctx, getPlayerStatsByName, arg.Name, arg.MatchType, arg.Season)
	var i GetPlayerStatsByNameRow
	err := row.Scan(
		&i.Name,
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
		&i.Points,
		&i.Played,
		&i.WinRate,
		&i.EfficiencyRate,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name, created_at, updated_at FROM players
ORDER BY name
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerName = `-- name: UpdatePlayerName :one
UPDATE players
SET 
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdatePlayerNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdatePlayerName(ctx context.Context, arg UpdatePlayerNameParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerName, arg.ID, arg.Name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerStatsLoss = `-- name: UpdatePlayerStatsLoss :one
UPDATE player_stats
SET 
    losses = losses + 1,
    streak = 0,
    scored = scored + $4,
    conceded = conceded + $5,
    updated_at = NOW()
WHERE player_id = $1
AND match_type = $2
AND season = $3
RETURNING id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded
`

type UpdatePlayerStatsLossParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
	Scored    int32     `json:"scored"`
	Conceded  int32     `json:"conceded"`
}

func (q *Queries) UpdatePlayerStatsLoss(ctx context.Context, arg UpdatePlayerStatsLossParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatsLoss,
		arg.PlayerID,
		arg.MatchType,
		arg.Season,
		arg.Scored,
		arg.Conceded,
	)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}

const updatePlayerStatsOtl = `-- name: UpdatePlayerStatsOtl :one
UPDATE player_stats
SET 
    otl = otl + 1,
    scored = scored + $4,
    conceded = conceded + $5,
    updated_at = NOW()
WHERE player_id = $1
AND match_type = $2
AND season = $3
RETURNING id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded
`

type UpdatePlayerStatsOtlParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
	Scored    int32     `json:"scored"`
	Conceded  int32     `json:"conceded"`
}

func (q *Queries) UpdatePlayerStatsOtl(ctx context.Context, arg UpdatePlayerStatsOtlParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatsOtl,
		arg.PlayerID,
		arg.MatchType,
		arg.Season,
		arg.Scored,
		arg.Conceded,
	)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}

const updatePlayerStatsWin = `-- name: UpdatePlayerStatsWin :one
UPDATE player_stats
SET 
    wins = wins + 1,
    streak = streak + 1,
    longest_streak = GREATEST(streak + 1, longest_streak),
    scored = scored + $4,
    conceded = conceded + $5,
    updated_at = NOW()
WHERE player_id = $1
AND match_type = $2
AND season = $3
RETURNING id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded
`

type UpdatePlayerStatsWinParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
	Scored    int32     `json:"scored"`
	Conceded  int32     `json:"conceded"`
}

func (q *Queries) UpdatePlayerStatsWin(ctx context.Context, arg UpdatePlayerStatsWinParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, updatePlayerStatsWin,
		arg.PlayerID,
		arg.MatchType,
		arg.Season,
		arg.Scored,
		arg.Conceded,
	)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}

const upsertPlayerStats = `-- name: UpsertPlayerStats :one
INSERT INTO player_stats (player_id, match_type, season) 
VALUES ($1, $2, $3)
ON CONFLICT (player_id, match_type, season) DO NOTHING
RETURNING id, player_id, match_type, season, wins, losses, otl, streak, longest_streak, scored, conceded
`

type UpsertPlayerStatsParams struct {
	PlayerID  uuid.UUID `json:"player_id"`
	MatchType string    `json:"match_type"`
	Season    int32     `json:"season"`
}

func (q *Queries) UpsertPlayerStats(ctx context.Context, arg UpsertPlayerStatsParams) (PlayerStat, error) {
	row := q.db.QueryRow(ctx, upsertPlayerStats, arg.PlayerID, arg.MatchType, arg.Season)
	var i PlayerStat
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.MatchType,
		&i.Season,
		&i.Wins,
		&i.Losses,
		&i.Otl,
		&i.Streak,
		&i.LongestStreak,
		&i.Scored,
		&i.Conceded,
	)
	return i, err
}
