// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddPlayerToMatch(ctx context.Context, arg AddPlayerToMatchParams) (MatchPlayer, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreatePlayer(ctx context.Context, name string) (Player, error)
	DeletePlayer(ctx context.Context, id uuid.UUID) error
	DeleteUncompletedMatch(ctx context.Context, id uuid.UUID) error
	GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error)
	GetMatch(ctx context.Context, id uuid.UUID) (Match, error)
	GetMatchPlayers(ctx context.Context, matchID uuid.UUID) ([]GetMatchPlayersRow, error)
	GetPlayerByID(ctx context.Context, id uuid.UUID) (Player, error)
	GetPlayerByName(ctx context.Context, name string) (Player, error)
	GetPlayerSeasonalMatches(ctx context.Context, arg GetPlayerSeasonalMatchesParams) ([]GetPlayerSeasonalMatchesRow, error)
	GetPlayerStatsByID(ctx context.Context, arg GetPlayerStatsByIDParams) (GetPlayerStatsByIDRow, error)
	GetPlayerStatsByName(ctx context.Context, arg GetPlayerStatsByNameParams) (GetPlayerStatsByNameRow, error)
	ListMatchesBySeason(ctx context.Context, arg ListMatchesBySeasonParams) ([]Match, error)
	ListPlayers(ctx context.Context) ([]Player, error)
	ListUncompletedMatches(ctx context.Context) ([]Match, error)
	UpdatePlayerName(ctx context.Context, arg UpdatePlayerNameParams) (Player, error)
	UpdatePlayerStatsLoss(ctx context.Context, arg UpdatePlayerStatsLossParams) (PlayerStat, error)
	UpdatePlayerStatsOtl(ctx context.Context, arg UpdatePlayerStatsOtlParams) (PlayerStat, error)
	UpdatePlayerStatsWin(ctx context.Context, arg UpdatePlayerStatsWinParams) (PlayerStat, error)
	UpsertPlayerStats(ctx context.Context, arg UpsertPlayerStatsParams) (PlayerStat, error)
}

var _ Querier = (*Queries)(nil)
